spring.application.name=computer-equipment-store-system-client
server.port=8081

backend.api.base-url=http://localhost:8080

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

spring.web.resources.static-locations=classpath:/static/

spring.cloud.openfeign.client.config.default.connectTimeout=5000
spring.cloud.openfeign.client.config.default.readTimeout=5000